// Developed by Mateo Pineda
export const aircraftSeeder = [
  {
    id: crypto.randomUUID(),
    registry: 'N737AM',
    model: 'B737-800',
    passengerCapacity: 160,
    status: 'active',
    firstFlightDate: new Date('2010-01-01'),
    imageURL: '@/public/images/aircrafts/aircraft-default.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    registry: 'N789DL',
    model: 'A320',
    passengerCapacity: 150,
    status: 'active',
    firstFlightDate: new Date('2012-05-15'),
    imageURL: '@/public/images/aircrafts/aircraft-default.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    registry: 'N452UA',
    model: 'B777-200',
    passengerCapacity: 280,
    status: 'maintenance',
    firstFlightDate: new Date('2005-09-10'),
    imageURL: '@/public/images/aircrafts/aircraft-default.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    registry: 'N610AF',
    model: 'A330-300',
    passengerCapacity: 250,
    status: 'retired',
    firstFlightDate: new Date('1998-03-22'),
    imageURL: '@/public/images/aircrafts/aircraft-default.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: crypto.randomUUID(),
    registry: 'N321BA',
    model: 'B747-400',
    passengerCapacity: 410,
    status: 'active',
    firstFlightDate: new Date('2000-11-05'),
    imageURL: '@/public/images/aircrafts/aircraft-default.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
